### PR TITLE
Chore: decommission `testing-mainnet` network

### PR DESCRIPTION
**Pull request by jpraynaud**
## Content

This PR includes the decommission of the `testing-mainnet` network which is no longer used.

## Pre-submit checklist

- Branch
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] No clippy warnings in the CI
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested

### CODE REVIEW

**Review by dlachaume — APPROVED** [review]
LGTM 🚀

**Review by sfauvel — APPROVED** [review]
LGTM

**Review by Alenar — APPROVED** [review]
LGTM :rocket: 

About the files still in the infrastructure (`mithril-infra/configuration/testing-mainnet`) do you want to delete them later ?

**Comment by jpraynaud** [comment]
> LGTM 🚀
> 
> About the files still in the infrastructure (`mithril-infra/configuration/testing-mainnet`) do you want to delete them later ?

Thanks for pointing that out, I have removed them in https://github.com/input-output-hk/mithril/pull/1978/commits/5642b6805567432a9af8646ecaa35d44ec65e913 :+1:

**Pull request merged**
