### PR TITLE
chore: add build target nodejs

### PR DESCRIPTION
**Pull request by fabianbormann**
Dear Mithril-team,

we need a commonjs package to run the mithril-client-wasm module within our ibc gateway setup. 

Would it be possible to bundle the module for the nodejs target as well and publishing it within your pipeline to the npm package regsitry? I added the needed line to your Makefile. 

Thanks for your support and keep up the great work ! 💪 
Fabian

### CODE REVIEW

**Comment by jpraynaud** [comment]
Hi @fabianbormann, thanks for creating this PR.

It will require some more work to implement a NodeJS compatible npm package for the Mithri client WASM.
I have created the issue #2091 for that :+1:

**Review by jpraynaud — APPROVED** [review]

**Review by sfauvel — APPROVED** [review]

**Review by dlachaume — APPROVED** [review]

**Review by Alenar — APPROVED** [review]

**Comment by jpraynaud** [comment]
@fabianbormann can you sign your commits as it is mandatory for merging on this repository?

**Comment by fabianbormann** [comment]
Sure will do

**Comment by fabianbormann** [comment]
@jpraynaud I signed the commit ✅

**Comment by jpraynaud** [comment]
Hi @fabianbormann, I see that the branch has conflicts and can not be merged as is.
Can you sync your fork and rebase your branch on main?

**Comment by fabianbormann** [comment]
@jpraynaud I'm done with resolving the conflicts 😊

**Comment by fabianbormann** [comment]
I don't know what went wrong, but after throwing the branch away and adding the line again it looks better now

https://github.com/input-output-hk/mithril/compare/main...fabianbormann:mithril:chore/add_nodejs_target

**Comment by jpraynaud** [comment]
> I don't know what went wrong, but after throwing the branch away and adding the line again it looks better now
> 
> [main...fabianbormann:mithril:chore/add_nodejs_target](https://github.com/input-output-hk/mithril/compare/main...fabianbormann:mithril:chore/add_nodejs_target)

All good now :tada: Once the CI run is green, I will merge the PR.
Thanks for the contribution @fabianbormann!

**Pull request merged**
