### PR TITLE
feat: Make `rug-backend` optional for `mithril-client` crate

### LINKED ISSUE #1786: Cargo Deny complains about LGPL-3.0 licenses
## Context & versions

`cargo deny check` complains that the mithril libraries rely on `LGPL-3.0+` licensed dependencies.

This is a problem for code because these libraries are statically linked, which means that any consumer can not produce a binary only version of the code.  As the LGPL requires that the program must be able to be relinked.

Output of `cargo deny check`
```
error[rejected]: failed to satisfy license requirements
  ┌─ registry+https://github.com/rust-lang/crates.io-index#gmp-mpfr-sys@1.6.4:4:12
  │
4 │ license = "LGPL-3.0+"
  │            ^^^^^^^^-
  │            │       │
  │            │       a GNU license was followed by a `+`
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license was not explicitly allowed
  │
  = LGPL-3.0 - GNU Lesser General Public License v3.0 only:
  =   - **DEPRECATED**
  =   - OSI approved
  =   - FSF Free/Libre
  =   - Copyleft
  = gmp-mpfr-sys v1.6.4
    └── rug v1.24.1
        └── mithril-stm v0.3.22
            └── mithril-common v0.4.14
                └── mithril-client v0.8.4
                    └── cardano-chain-follower v0.1.0
                        └── hermes v0.0.1

error[rejected]: failed to satisfy license requirements
  ┌─ registry+https://github.com/rust-lang/crates.io-index#rug@1.24.1:4:12
  │
4 │ license = "LGPL-3.0+"
  │            ^^^^^^^^-
  │            │       │
  │            │       a GNU license was followed by a `+`
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license was not explicitly allowed
  │
  = LGPL-3.0 - GNU Lesser General Public License v3.0 only:
  =   - **DEPRECATED**
  =   - OSI approved
  =   - FSF Free/Libre
  =   - Copyleft
  = rug v1.24.1
    └── mithril-stm v0.3.22
        └── mithril-common v0.4.14
            └── mithril-client v0.8.4
                └── cardano-chain-follower v0.1.0
                    └── hermes v0.0.1
```
## Steps to reproduce

Run `cargo deny check  --exclude-dev` on the code.

## Actual behavior

Links against LGPL code without the option to select it.

## Expected behavior

The libraries in-question have non LGPL counterparts already but there is no way to select them, its automatically chosen based on architecture.

It would be nice to expose a feature flag to control which library is used.

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
## Content

To allow disable `LGPL` usage which discussed [in](https://github.com/input-output-hk/mithril/issues/1786), added `rug-backend` feature for `mithril-client` and `mithril-common` crates.

## Issue(s)

Closes #1786

### CODE REVIEW

**Comment by Mr-Leshiy** [comment]
About the CI failure.
I've run this `hash_computation_is_quicker_with_a_full_cache` test locally and it passes.
Also seems to me that what testing under this test is not actually related to my changes.
So to be honest dont know what to do with it.

**Review by jpraynaud — APPROVED** [review]
LGTM :+1: 

@Mr-Leshiy, thank you for the contribution!

Before we can merge your PR, could you?
- tidy up a bit the commit history as we don't squash commits when merging
- add an entry in the `CHANGELOG.md` file at the root of the repository for this new feature
- bump the patch versions of `mithril-client`, `mithril-common` and `mithril-stm`

**Review by Alenar — APPROVED** [review]
LGTM.

I would have really liked to avoid using `default-features = false` for the `mithril-common` import in `mithril-client`, but as much as I can scratch my head there's no acceptable alternatives that come in mind.

**Comment by Mr-Leshiy** [comment]
@jpraynaud 

Thanks for your feedback !

I've made requested changes for `CHANGLELOG.md` file, bumping versions and squashing commits.

**Comment by jpraynaud** [comment]
@Mr-Leshiy actually your [commits need to be signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) in order to be merged in the `main` branch.
Can you re-push them with your signature?

**Comment by jpraynaud** [comment]
Hi @Mr-Leshiy, on top of signing the commits, could you also sync your fork and make sure that the crates versions in your PR have not already been used by another PR in the mean time?

**Comment by Mr-Leshiy** [comment]
@jpraynaud done 🚀

**Pull request merged**
